[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm ci",
  "npm --prefix frontend ci"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build",
  "npm --prefix frontend run build"
]

[start]
cmd = "node dist/main"
